spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    open-in-view: false
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
springdoc:
  swagger-ui:
    path: index
catalog:
  page-size: 10
